version: '3.5'

services:
  # postgres:
  #   image: postgres:12-alpine
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USERNAME: postgres
  #     POSTGRES_DB: jupiter
  #   networks:
  #     - app
  dev:
    build: 
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    networks:
      - app
    ports:
      - 3000:3000
    # depends_on:
    #   - postgres
    command: [sh, -c, 'npm run start:dev']
    volumes:
      - .:/app:delegated
      - /app/node_modules

networks:
  app: